### PR TITLE
Elements

### PR DESCRIPTION
**Pull request by MrTheGood**
Add all the UI elements.
See comments for screenshots

### CODE REVIEW

**Comment by MrTheGood** [comment]
Screenshot 2019-12-07 at 20 59 54
LOGIN

**Comment by MrTheGood** [comment]
Screenshot 2019-12-07 at 20 59 59
RESET PASSWORD

**Comment by MrTheGood** [comment]
Screenshot 2019-12-07 at 21 00 02
SIGN UP

**Comment by MrTheGood** [comment]
Screenshot 2019-12-07 at 21 00 08
TIMELINE INCLUDING THE POST FABS (posting still requires some kind of dialog but i'm sure you'll figure that out)

**Comment by MrTheGood** [comment]
Screenshot 2019-12-07 at 21 00 50
VerticalProfileView  



Screenshot 2019-12-07 at 21 00 55
HorizontalProfileView

**Comment by MrTheGood** [comment]
Screenshot 2019-12-07 at 21 01 19
PROFILE

**Comment by MrTheGood** [comment]
Screenshot 2019-12-07 at 21 01 42
Screenshot 2019-12-07 at 21 01 55
And all the buttons on the profile

**Review by CJVisser — APPROVED** [review]

**Pull request merged**
